# build_ticker_list.py
# -*- coding: utf-8 -*-

"""
Generate a broad list of U.S. tickers using yahoo_fin and write them to ticker_list.py.

Sources combined:
  - S&P 500
  - NASDAQ (full)
  - Dow 30
  - "Other" (NYSE/AMEX/OTC tracked by Yahoo)

Improvements:
  - Normalize tickers for Yahoo: '.' -> '-', uppercase, strip
  - Exclude suffixes: W (warrants), R (rights), P (preferred), Q (bankrupt)
  - Optional: keep only [A-Z0-9-] up to length 6 (adjust if needed)

Usage:
  python build_ticker_list.py
"""

import re
import sys
from typing import Iterable, Set

import pandas as pd
from yahoo_fin import stock_info as si


EXCLUDE_SUFFIXES = {"W", "R", "P", "Q"}

# Allow letters, digits, and hyphen (for classes like BRK-B). Max length can be tuned.
PLAIN_TICKER_RE = re.compile(r"^[A-Z0-9-]{1,6}$")


def _to_set(values: Iterable[str]) -> Set[str]:
    return set(pd.Series(values).dropna().astype(str).tolist())


def fetch_raw_universe() -> Set[str]:
    """Fetch raw symbols from multiple yahoo_fin universes and union them."""
    df1 = pd.DataFrame(si.tickers_sp500())
    df2 = pd.DataFrame(si.tickers_nasdaq())
    df3 = pd.DataFrame(si.tickers_dow())
    df4 = pd.DataFrame(si.tickers_other())

    sym1 = _to_set(df1[0])
    sym2 = _to_set(df2[0])
    sym3 = _to_set(df3[0])
    sym4 = _to_set(df4[0])

    return sym1 | sym2 | sym3 | sym4


def normalize_symbol(s: str) -> str:
    """Normalize symbol for Yahoo: replace '.' with '-', uppercase, strip."""
    return s.strip().upper().replace(".", "-")


def is_excluded_suffix(s: str) -> bool:
    """Exclude tickers ending with W/R/P/Q when length > 4."""
    return len(s) > 4 and s[-1] in EXCLUDE_SUFFIXES


def is_plain_ticker(s: str) -> bool:
    """
    Keep only alphanumeric + '-' up to 6 chars to reduce exotic/OTC noise.
    Adjust the length if you want to allow longer symbols.
    """
    return bool(PLAIN_TICKER_RE.fullmatch(s))


def build_clean_universe() -> Set[str]:
    raw = fetch_raw_universe()
    cleaned = set()

    for sym in raw:
        s = normalize_symbol(sym)

        # Filter out suffix classes we don't want for equities
        if is_excluded_suffix(s):
            continue

        # Optional: restrict to plain tickers to avoid exotic symbols
        if not is_plain_ticker(s):
            continue

        cleaned.add(s)

    return cleaned


def write_ticker_list_py(symbols: Set[str], out_path: str = "ticker_list.py") -> None:
    ordered = sorted(symbols)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("# Auto-generated by build_ticker_list.py\n")
        f.write(f"# Universe size: {len(ordered)}\n\n")
        f.write("tickers = [\n")
        for t in ordered:
            f.write(f'    "{t}",\n')
        f.write("]\n")
    print(f"Wrote {out_path} with {len(ordered)} tickers.")


def main():
    try:
        all_symbols = build_clean_universe()
    except Exception as e:
        print(f"Failed to build ticker list: {e}", file=sys.stderr)
        sys.exit(1)

    print(f"Total valid tickers: {len(all_symbols)}")
    write_ticker_list_py(all_symbols)


if __name__ == "__main__":
    main()
